version: '2'

services:
  
  backend:
    build:
      context: ./backend/src/main/docker/
    container_name: backend
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
    networks:
      - test-network

  frontend:
    build:
      context: ./frontend/
    container_name: frontend
    ports:
      - "5173:5173"
    networks:
      - test-network

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    networks:
      - test-network

networks:
  test-network:
    driver: bridge